version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      microblog-network: {}

  php:
    build:
      context: ./docker
      dockerfile: ./php/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    networks:
      microblog-network: {}

  mysql:
    image: mysql:8.3.0
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: MicroblogDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      microblog-network: {}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - "3400:80"
    networks:
      microblog-network: {}
    
  node:
    build:
      context: ./src 
      dockerfile: ../docker/node/Dockerfile  
    volumes:
      - ./src:/var/www/html
    networks:
      - microblog-network
    command: sh -c "npm install && npm run dev"

networks:
  microblog-network: 
    driver: bridge

volumes:
  mysql-data: {}
